/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 earth.gltf 
Author: LuizZed36 (https://sketchfab.com/LuizZed36)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/koenigsegg-jesko-cafb4f09b0694b2f9614b4289ae717b8
Title: Koenigsegg Jesko
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/earth.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.BODY_NUMBER_CARBON} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.CABIN} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.CALIPER} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.CARBON_FIBER} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.CAR_BODY_PAINT} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.DISCS} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.GRILLS} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.LIGHTS_GLASS} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.LIGHTS_POD} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.LIGHTS_SATIN} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.MATT} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.SHINY_METAL} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.SUSPENSION} />
        <mesh geometry={nodes.Object_15.geometry} material={materials.TARMAC_TYRE_TREAD} />
        <mesh geometry={nodes.Object_16.geometry} material={materials.TARMAC_TYRE_WALL} />
        <mesh geometry={nodes.Object_17.geometry} material={materials.TARMAC_WHEEL} />
        <mesh geometry={nodes.Object_18.geometry} material={materials.WINDOW_GLASS} />
      </group>
    </group>
  )
}

useGLTF.preload('/earth.gltf')
