/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 .\earth.gltf 
Author: KWHNDR (https://sketchfab.com/kwhndr)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/unmarked-ford-explorer-3db29278d23c42ab80cc14808a69e828
Title: Unmarked Ford Explorer
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model(props) {
  const { nodes, materials } = useGLTF('/earth.gltf')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <group position={[-0.001, 0, 0]} scale={27.891}>
            <mesh geometry={nodes.Glass_WindShield_0.geometry} material={materials.WindShield} />
            <mesh geometry={nodes.Glass_HeadLightGlass_0.geometry} material={materials.HeadLightGlass} />
          </group>
          <group position={[-0.001, 0, 0]} scale={27.891}>
            <mesh geometry={nodes.Cage_BullBarsMetal_0.geometry} material={materials.BullBarsMetal} />
            <mesh geometry={nodes.Cage_Glass_0.geometry} material={materials.Glass} />
          </group>
          <group position={[-68.444, 109.26, 43.187]} scale={27.891}>
            <mesh geometry={nodes['SteeringWheel_Buttons(_0'].geometry} material={materials.Buttons} />
            <mesh geometry={nodes.SteeringWheel_FordLogo_0.geometry} material={materials.FordLogo} />
            <mesh geometry={nodes.SteeringWheel_PlasticMidShine_0.geometry} material={materials.PlasticMidShine} />
            <mesh geometry={nodes.SteeringWheel_Chrome_0.geometry} material={materials.Chrome} />
          </group>
          <group position={[-0.001, 0, 0]} scale={27.891}>
            <mesh geometry={nodes.CarShell_PlasticMidShine_0.geometry} material={materials.PlasticMidShine} />
            <mesh geometry={nodes.CarShell_PlasticMidShine_0_1.geometry} material={materials.PlasticMidShine} />
            <mesh geometry={nodes.CarShell_PlasticShine_0.geometry} material={materials.PlasticShine} />
            <mesh geometry={nodes.CarShell_FordLogo_0.geometry} material={materials.FordLogo} />
            <mesh geometry={nodes.CarShell_ChromeShine_0.geometry} material={materials.ChromeShine} />
            <mesh geometry={nodes.CarShell_HeadLightGlass_0.geometry} material={materials.HeadLightGlass} />
            <mesh geometry={nodes.CarShell_RedShine_0.geometry} material={materials.RedShine} />
          </group>
          <group position={[-0.001, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.FrontBulbs2001_YellowGlassEmissionAmbient_0.geometry} material={materials.YellowGlassEmissionAmbient} />
            <mesh geometry={nodes.FrontBulbs2001_YellowGlassEmission_0.geometry} material={materials.YellowGlassEmission} />
            <mesh geometry={nodes.FrontBulbs2001_YellowGlass_0.geometry} material={materials.YellowGlass} />
            <mesh geometry={nodes.FrontBulbs2001_Glass_0.geometry} material={materials.Glass} />
          </group>
          <group rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.SideMirror_PlasticMidShine_0.geometry} material={materials.PlasticMidShine} />
            <mesh geometry={nodes.SideMirror_ChromeShine_0.geometry} material={materials.ChromeShine} />
          </group>
          <group position={[-0.001, 0, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes.TailLight_ChromeShine_0.geometry} material={materials.ChromeShine} />
            <mesh geometry={nodes.TailLight_YellowGlass_0.geometry} material={materials.YellowGlass} />
            <mesh geometry={nodes.TailLight_BerkGlasssRed_0.geometry} material={materials.BerkGlasssRed} />
            <mesh geometry={nodes.TailLight_HeadLightGlass_0.geometry} material={materials.HeadLightGlass} />
            <mesh geometry={nodes.TailLight_White_0.geometry} material={materials.White} />
            <mesh geometry={nodes.TailLight_EmissionRed_0.geometry} material={materials.EmissionRed} />
            <mesh geometry={nodes.TailLight_PlasticMidShine_0.geometry} material={materials.PlasticMidShine} />
          </group>
          <group position={[-0.001, 0, 0]} scale={27.891}>
            <mesh geometry={nodes.Sirens001_TexturesLightsOFF_0.geometry} material={materials.TexturesLightsOFF} />
            <mesh geometry={nodes.Sirens001_PlasticMidShine_0.geometry} material={materials.PlasticMidShine} />
          </group>
          <group position={[131.785, 41.68, 87.047]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes['FirestoneTire-Explorer2001_FirestoneTires_0'].geometry} material={materials.FirestoneTires} />
            <mesh geometry={nodes['FirestoneTire-Explorer2001_Rim_0'].geometry} material={materials.material} />
            <mesh geometry={nodes['FirestoneTire-Explorer2001_Brake_Disc_0'].geometry} material={materials.Brake_Disc} />
            <mesh geometry={nodes['FirestoneTire-Explorer2001_Brembo_Calipers_0'].geometry} material={materials.Brembo_Calipers} />
            <mesh geometry={nodes['FirestoneTire-Explorer2001_Hubcap_0'].geometry} material={materials.Hubcap} />
            <mesh geometry={nodes['FirestoneTire-Explorer2001_PlasticMidShine_0'].geometry} material={materials.PlasticMidShine} />
          </group>
          <group position={[-172.496, 41.68, 84.983]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
            <mesh geometry={nodes['FirestoneTire-Explorer2002_FirestoneTires_0'].geometry} material={materials.FirestoneTires} />
            <mesh geometry={nodes['FirestoneTire-Explorer2002_Rim_0'].geometry} material={materials.material} />
            <mesh geometry={nodes['FirestoneTire-Explorer2002_Brake_Disc_0'].geometry} material={materials.Brake_Disc} />
            <mesh geometry={nodes['FirestoneTire-Explorer2002_Brembo_Calipers_0'].geometry} material={materials.Brembo_Calipers} />
            <mesh geometry={nodes['FirestoneTire-Explorer2002_Hubcap_0'].geometry} material={materials.Hubcap} />
            <mesh geometry={nodes['FirestoneTire-Explorer2002_PlasticMidShine_0'].geometry} material={materials.PlasticMidShine} />
          </group>
          <group position={[131.785, 41.68, -87.047]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[-100, 100, 100]}>
            <mesh geometry={nodes['FirestoneTire-Explorer2003_FirestoneTires_0'].geometry} material={materials.FirestoneTires} />
            <mesh geometry={nodes['FirestoneTire-Explorer2003_Rim_0'].geometry} material={materials.material} />
            <mesh geometry={nodes['FirestoneTire-Explorer2003_Brake_Disc_0'].geometry} material={materials.Brake_Disc} />
            <mesh geometry={nodes['FirestoneTire-Explorer2003_Brembo_Calipers_0'].geometry} material={materials.Brembo_Calipers} />
            <mesh geometry={nodes['FirestoneTire-Explorer2003_Hubcap_0'].geometry} material={materials.Hubcap} />
            <mesh geometry={nodes['FirestoneTire-Explorer2003_PlasticMidShine_0'].geometry} material={materials.PlasticMidShine} />
          </group>
          <group position={[-172.496, 41.68, -84.983]} rotation={[-Math.PI / 2, 0, -Math.PI]} scale={[-100, 100, 100]}>
            <mesh geometry={nodes['FirestoneTire-Explorer2004_FirestoneTires_0'].geometry} material={materials.FirestoneTires} />
            <mesh geometry={nodes['FirestoneTire-Explorer2004_Rim_0'].geometry} material={materials.material} />
            <mesh geometry={nodes['FirestoneTire-Explorer2004_Brake_Disc_0'].geometry} material={materials.Brake_Disc} />
            <mesh geometry={nodes['FirestoneTire-Explorer2004_Brembo_Calipers_0'].geometry} material={materials.Brembo_Calipers} />
            <mesh geometry={nodes['FirestoneTire-Explorer2004_Hubcap_0'].geometry} material={materials.Hubcap} />
            <mesh geometry={nodes['FirestoneTire-Explorer2004_PlasticMidShine_0'].geometry} material={materials.PlasticMidShine} />
          </group>
          <mesh geometry={nodes.Motorola_XTL1_Radio_0.geometry} material={materials.Radio} position={[-0.001, 0, 0]} scale={27.891} />
          <mesh geometry={nodes.Printer_PlasticMidShine_0.geometry} material={materials.PlasticMidShine} position={[-0.001, 0, 0]} scale={27.891} />
          <mesh geometry={nodes.Police_Pad_Control_0.geometry} material={materials.Control} position={[-0.001, 0, 0]} scale={27.891} />
          <mesh geometry={nodes.Controller_PlasticMidShine_0.geometry} material={materials.PlasticMidShine} scale={27.891} />
          <mesh geometry={nodes.PanasonicDashcam_PlasticMidShine_0.geometry} material={materials.PlasticMidShine} position={[-0.001, 0, 0]} scale={27.891} />
          <mesh geometry={nodes.Body_CarPaint_0.geometry} material={materials.CarPaint} scale={27.891} />
          <mesh geometry={nodes.FrontLogo_Chrome_0.geometry} material={materials.Chrome} position={[-0.001, 0, 0]} scale={27.891} />
          <mesh geometry={nodes.HeadLight_Emission_0.geometry} material={materials.Emission} position={[-219.627, 95.874, 0.907]} scale={27.891} />
          <mesh geometry={nodes.Closers_PlasticMidShine_0.geometry} material={materials.PlasticMidShine} position={[-257.545, 58.247, 0.028]} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Betana_PlasticMidShine_0.geometry} material={materials.PlasticMidShine} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Cage2_BullBarsMetal_0.geometry} material={materials.BullBarsMetal} rotation={[-Math.PI / 2, 0, 0]} scale={100} />
          <mesh geometry={nodes.Body2_CarPaint_0.geometry} material={materials.CarPaint} position={[-204.525, 117.078, 0]} scale={27.891} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/earth.gltf')