'use client';
import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Providers } from "./providers";
import Footer from "@/components/Footer";
import { IoLogoWhatsapp } from "react-icons/io";
import { Sora } from "next/font/google";
import { usePathname } from "next/navigation";
import Image from "next/image";
import whatsapp from "@/assets/whatsapp.png"

const sora = Sora({ subsets: ["latin"] });

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export default function RootLayout({ children }) {
  // Metadata for the layout (not exported)
  const metadata = {
    title: "CAMIO-PPF",
    description: "Generated by create next app",
  };

  const pathname = usePathname();
  const isAdminRoute = pathname.startsWith("/admin");

  return (
    <html lang="en">
      <head>
        {/* Setting the title and description within <head> */}
        <title>{metadata.title}</title>
        <meta name="description" content={metadata.description} />
      </head>
      <body className={`${sora.className} antialiased overflow-x-hidden`}>
        <Providers>
          {/* Render Navbar, WhatsApp icon, and Footer only if not on /admin routes */}
          {!isAdminRoute && <Navbar />}
          {children}
          {!isAdminRoute && (
            <a
              href="https://wa.me/728377971?text=awesome product"
              target="_blank"
              aria-label="Message us on WhatsApp about this awesome product"
            >
              <div className="bg-white p-2">
                <Image width={50} height={50} alt="whatsapp" src={whatsapp} className="text-[50px] p-1 fixed bottom-14 right-14 text-green-400"/>
              </div>
            </a>
          )}
          {!isAdminRoute && <Footer />}
        </Providers>
      </body>
    </html>
  );
}
